import { useCallback, useEffect, useState } from 'react';
import { FiEdit2, FiStar, FiTrash2 } from 'react-icons/fi';
import { Link } from 'react-router-dom';

import Button from '@/components/ui/Button';
import EmptyState from '@/components/ui/EmptyState';
import Loader from '@/components/ui/Loader';
import { ROUTES } from '@/constants/routes';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/useToast';
import { createReview, deleteReview, getReviews, updateReview } from '@/services/review.service';

const EMPTY_FORM = { rating: 5, title: '', comment: '' };
function Stars({ rating, interactive = false, onChange }) { return <div className="flex gap-1" aria-label={`${rating} out of 5 stars`}>{[1, 2, 3, 4, 5].map((value) => <button key={value} type="button" disabled={!interactive} onClick={() => onChange?.(value)} className={interactive ? 'cursor-pointer' : 'cursor-default'}><FiStar className={value <= rating ? 'fill-champagne-gold text-champagne-gold' : 'text-matte-black/20'} /></button>)}</div>; }
function ReviewSection({ productId }) {
  const { currentUser, isAuthenticated } = useAuth(); const { showToast } = useToast();
  const [data, setData] = useState({ reviews: [], averageRating: 0, reviewCount: 0 }); const [loading, setLoading] = useState(true); const [form, setForm] = useState(EMPTY_FORM); const [editingId, setEditingId] = useState(''); const [submitting, setSubmitting] = useState(false);
  const load = useCallback(async () => { setLoading(true); try { setData(await getReviews(productId)); } catch (error) { showToast(error.message || 'Unable to load reviews.', 'error'); } finally { setLoading(false); } }, [productId, showToast]);
  useEffect(() => { load(); }, [load]);
  const submit = async (event) => { event.preventDefault(); setSubmitting(true); try { const next = editingId ? await updateReview(editingId, form) : await createReview(productId, form); setData(next); setForm(EMPTY_FORM); setEditingId(''); showToast(editingId ? 'Review updated.' : 'Thank you for your review.', 'success'); } catch (error) { showToast(error.message || 'Unable to save review.', 'error'); } finally { setSubmitting(false); } };
  const edit = (review) => { setEditingId(review.id); setForm({ rating: review.rating, title: review.title, comment: review.comment }); };
  const remove = async (id) => { try { setData(await deleteReview(id)); showToast('Review removed.', 'success'); } catch (error) { showToast(error.message || 'Unable to remove review.', 'error'); } };
  const userName = (review) => `${review.user?.firstName || ''} ${review.user?.lastName || ''}`.trim() || 'DESTEOR customer';
  return <section className="border-t border-matte-black/10 pt-16 md:pt-24"><div className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-xs font-semibold uppercase tracking-[0.28em] text-champagne-gold">Customer notes</p><h2 className="mt-2 text-3xl text-matte-black">Reviews</h2></div><div className="flex items-center gap-3"><Stars rating={Math.round(data.averageRating)} /><span className="text-sm text-matte-black/60">{data.averageRating.toFixed(1)} · {data.reviewCount} reviews</span></div></div>
    {isAuthenticated ? <form onSubmit={submit} className="mt-8 grid gap-4 border border-matte-black/10 bg-white p-5"><div className="flex items-center justify-between"><p className="font-semibold text-matte-black">{editingId ? 'Edit your review' : 'Share your experience'}</p><Stars rating={form.rating} interactive onChange={(rating) => setForm((value) => ({ ...value, rating }))} /></div><input required maxLength="120" value={form.title} onChange={(event) => setForm((value) => ({ ...value, title: event.target.value }))} placeholder="Review title" className="border border-matte-black/15 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-champagne-gold" /><textarea required minLength="10" maxLength="2000" value={form.comment} onChange={(event) => setForm((value) => ({ ...value, comment: event.target.value }))} placeholder="Tell us what you loved" rows="4" className="border border-matte-black/15 px-4 py-3 text-sm focus:outline-none focus:ring-2 focus:ring-champagne-gold" /><div className="flex gap-3"><Button type="submit" variant="secondary" className="rounded-none" disabled={submitting}>{submitting ? 'Saving...' : editingId ? 'Update review' : 'Submit review'}</Button>{editingId && <Button type="button" variant="ghost" className="rounded-none" onClick={() => { setEditingId(''); setForm(EMPTY_FORM); }}>Cancel</Button>}</div></form> : <div className="mt-8 border border-matte-black/10 bg-white p-5 text-sm text-matte-black/65">Please <Link className="font-semibold text-champagne-gold" to={ROUTES.LOGIN}>sign in</Link> to leave a review.</div>}
    <div className="mt-10 space-y-5">{loading ? <Loader label="Loading reviews" /> : data.reviews.length ? data.reviews.map((review) => <article key={review.id} className="border-b border-matte-black/10 pb-5"><div className="flex flex-wrap justify-between gap-3"><div><div className="flex items-center gap-3"><Stars rating={review.rating} /><span className="text-sm font-semibold text-matte-black">{review.title}</span></div><p className="mt-2 text-sm text-matte-black/60">{userName(review)} · {new Date(review.createdAt).toLocaleDateString()}</p></div>{currentUser?.id === review.userId && <div className="flex gap-2"><button type="button" onClick={() => edit(review)} className="text-matte-black/50 hover:text-champagne-gold" aria-label="Edit review"><FiEdit2 /></button><button type="button" onClick={() => remove(review.id)} className="text-matte-black/50 hover:text-red-600" aria-label="Delete review"><FiTrash2 /></button></div>}</div><p className="mt-4 text-sm leading-7 text-matte-black/70">{review.comment}</p></article>) : <EmptyState title="No reviews yet" description="Be the first to share your experience with this piece." />}</div></section>;
}
export default ReviewSection;
