const adminRepository = require('../repositories/admin.repository');

const ORDER_STATUSES = ['PENDING', 'PROCESSING', 'PACKED', 'SHIPPED', 'DELIVERED', 'CANCELLED'];
const NEXT_STATUS = { PENDING: ['PROCESSING', 'CANCELLED'], PROCESSING: ['PACKED', 'CANCELLED'], PACKED: ['SHIPPED', 'CANCELLED'], SHIPPED: ['DELIVERED', 'CANCELLED'], DELIVERED: [], CANCELLED: [] };

function createError(message, statusCode = 400) { const error = new Error(message); error.statusCode = statusCode; return error; }
function pagination(query) { const page = Math.max(1, Number.parseInt(query.page, 10) || 1); const limit = Math.min(50, Math.max(1, Number.parseInt(query.limit, 10) || 12)); return { page, limit, skip: (page - 1) * limit }; }
function meta(total, page, limit) { const totalPages = Math.max(1, Math.ceil(total / limit)); return { total, page, limit, totalPages, hasNextPage: page < totalPages, hasPreviousPage: page > 1 }; }
function mapProduct(product) { return product; }
function productData(input) {
  const { images = [], specifications = [], categoryId, collectionId, ...fields } = input;
  return { ...fields, category: { connect: { id: categoryId } }, collection: { connect: { id: collectionId } }, images: { create: images.map((image, index) => ({ url: image.url, cloudinaryPublicId: image.publicId || image.cloudinaryPublicId || null, altText: image.altText || null, displayOrder: image.displayOrder ?? index })) }, specifications: { create: specifications.map((specification, index) => ({ label: specification.label, value: specification.value, displayOrder: specification.displayOrder ?? index })) } };
}
function productUpdateData(input) {
  const { images, specifications, categoryId, collectionId, ...fields } = input;
  const data = { ...fields };
  if (categoryId) data.category = { connect: { id: categoryId } };
  if (collectionId) data.collection = { connect: { id: collectionId } };
  if (images) data.images = { deleteMany: {}, create: images.map((image, index) => ({ url: image.url, cloudinaryPublicId: image.publicId || image.cloudinaryPublicId || null, altText: image.altText || null, displayOrder: image.displayOrder ?? index })) };
  if (specifications) data.specifications = { deleteMany: {}, create: specifications.map((specification, index) => ({ label: specification.label, value: specification.value, displayOrder: specification.displayOrder ?? index })) };
  return data;
}

async function getDashboard() { const [users, products, orders, grouped, categories, collections] = await adminRepository.getDashboardCounts(); const [categoryGroups, categoryRows, deliveredOrders] = await adminRepository.getDashboardCharts(); const byStatus = Object.fromEntries(grouped.map((item) => [item.status, item._count._all])); const names = Object.fromEntries(categoryRows.map((item) => [item.id, item.name])); const revenue = {}; deliveredOrders.forEach((item) => { const key = item.createdAt.toISOString().slice(0, 7); revenue[key] = (revenue[key] || 0) + item.total; }); return { totalUsers: users, totalProducts: products, totalOrders: orders, totalCategories: categories, totalCollections: collections, ...Object.fromEntries(ORDER_STATUSES.map((status) => [status.toLowerCase(), byStatus[status] || 0])), charts: { ordersByStatus: ORDER_STATUSES.map((status) => ({ label: status, value: byStatus[status] || 0 })), productsByCategory: categoryGroups.map((item) => ({ label: names[item.categoryId], value: item._count._all })), monthlyRevenue: Object.entries(revenue).sort(([a], [b]) => a.localeCompare(b)).map(([label, value]) => ({ label, value })) } }; }
async function getProducts(query) { const { page, limit, skip } = pagination(query); const search = query.search?.trim(); const where = { ...(search && { OR: [{ name: { contains: search, mode: 'insensitive' } }, { slug: { contains: search, mode: 'insensitive' } }] }), ...(query.categoryId && { categoryId: query.categoryId }), ...(query.collectionId && { collectionId: query.collectionId }), ...(query.featured === 'true' && { featured: true }), ...(query.stock === 'in-stock' && { stock: { gt: 0 } }), ...(query.stock === 'out-of-stock' && { stock: 0 }) }; const orderBy = query.sort === 'name' ? { name: 'asc' } : query.sort === 'price-low' ? { price: 'asc' } : query.sort === 'price-high' ? { price: 'desc' } : { createdAt: 'desc' }; const [total, products] = await adminRepository.findProducts({ where, orderBy, skip, take: limit }); return { products: products.map(mapProduct), meta: meta(total, page, limit) }; }
async function getProduct(id) { const product = await adminRepository.findProduct(id); if (!product) throw createError('Product not found.', 404); return product; }
async function createProduct(input) { return adminRepository.createProduct(productData(input)); }
async function deleteCloudinaryImages(images) { const { deleteImage } = require('./media.service'); await Promise.all(images.filter((image) => image.cloudinaryPublicId).map((image) => deleteImage(image.cloudinaryPublicId))); }
async function updateProduct(id, input) { const existing = await getProduct(id); if (input.images) { const retainedPublicIds = new Set(input.images.map((image) => image.cloudinaryPublicId)); await deleteCloudinaryImages(existing.images.filter((image) => !retainedPublicIds.has(image.cloudinaryPublicId))); } return adminRepository.updateProduct(id, productUpdateData(input)); }
async function removeProduct(id) { const product = await getProduct(id); const [cartItems, orderItems] = await adminRepository.getProductReferenceCounts(id); if (cartItems || orderItems) throw createError('This product cannot be deleted because it is referenced by cart or order records.', 409); await deleteCloudinaryImages(product.images); await adminRepository.deleteProduct(id); }
async function getTaxonomies(type) { return adminRepository.findTaxonomies(type); }
async function createTaxonomy(type, data) { return adminRepository.createTaxonomy(type, data); }
async function updateTaxonomy(type, id, data) { const existing = await adminRepository.findTaxonomy(type, id); if (!existing) throw createError(`${type === 'category' ? 'Category' : 'Collection'} not found.`, 404); return adminRepository.updateTaxonomy(type, id, data); }
async function removeTaxonomy(type, id) { const existing = await adminRepository.findTaxonomy(type, id); const label = type === 'category' ? 'Category' : 'Collection'; if (!existing) throw createError(`${label} not found.`, 404); if (existing._count.products) throw createError(`${label} cannot be deleted while it contains products.`, 409); await adminRepository.deleteTaxonomy(type, id); }
async function getOrders(query) { const { page, limit, skip } = pagination(query); const where = { ...(query.status && { status: query.status }), ...(query.search && { orderNumber: { contains: query.search.trim(), mode: 'insensitive' } }) }; const [total, orders] = await adminRepository.findOrders({ where, orderBy: { createdAt: query.sort === 'oldest' ? 'asc' : 'desc' }, skip, take: limit }); return { orders, meta: meta(total, page, limit) }; }
async function getOrder(id) { const order = await adminRepository.findOrder(id); if (!order) throw createError('Order not found.', 404); return order; }
async function changeOrderStatus(id, status) { const order = await getOrder(id); if (!NEXT_STATUS[order.status].includes(status)) throw createError(`Cannot change an order from ${order.status} to ${status}.`, 422); return adminRepository.updateOrderStatus(id, status); }
async function getUsers(query) { const { page, limit, skip } = pagination(query); const search = query.search?.trim(); const where = { ...(query.role && { role: query.role }), ...(search && { OR: [{ firstName: { contains: search, mode: 'insensitive' } }, { lastName: { contains: search, mode: 'insensitive' } }, { email: { contains: search, mode: 'insensitive' } }] }) }; const [total, users] = await adminRepository.findUsers({ where, skip, take: limit }); return { users, meta: meta(total, page, limit) }; }
async function changeUserRole(adminId, userId, role) { const user = await adminRepository.findUser(userId); if (!user) throw createError('User not found.', 404); if (adminId === userId && role !== 'ADMIN') throw createError('You cannot remove your own administrator role.', 422); return adminRepository.updateUser(userId, { role }); }
async function removeUser(adminId, userId) { const user = await adminRepository.findUser(userId); if (!user) throw createError('User not found.', 404); if (adminId === userId) throw createError('You cannot delete your own account.', 422); if (user._count.orders) throw createError('Users with existing orders cannot be deleted.', 409); await adminRepository.deleteUser(userId); }
async function updateProfile(userId, input) { const data = {}; ['firstName', 'lastName', 'phone', 'profileImage'].forEach((field) => { if (input[field] !== undefined) data[field] = input[field]; }); if (input.password) { const { hashPassword } = require('../utils/hash'); data.password = await hashPassword(input.password); } return adminRepository.updateUser(userId, data); }

module.exports = { getDashboard, getProducts, getProduct, createProduct, updateProduct, removeProduct, getTaxonomies, createTaxonomy, updateTaxonomy, removeTaxonomy, getOrders, getOrder, changeOrderStatus, getUsers, changeUserRole, removeUser, updateProfile };
