const express = require('express');
const controller = require('../controllers/admin.controller');
const { protect, requireRole } = require('../middleware/auth.middleware');
const { validateProduct, validateTaxonomy, validateStatus, validateRole, validateProfile } = require('../validators/admin.validator');
const { uploadImages } = require('../middleware/upload.middleware');
const router = express.Router();
router.use(protect, requireRole('ADMIN'));
router.get('/dashboard', controller.dashboard);
router.post('/upload', uploadImages, controller.upload);
router.delete('/upload', controller.deleteUpload);
router.get('/profile', (req, res) => res.status(200).json({ success: true, data: { user: req.user } }));
router.patch('/profile', validateProfile, controller.updateProfile);
router.get('/users', controller.users);
router.patch('/users/:id/role', validateRole, controller.updateUserRole);
router.delete('/users/:id', controller.deleteUser);
router.route('/products').get(controller.products).post(validateProduct, controller.createProduct);
router.route('/products/:id').get(controller.product).put(validateProduct, controller.updateProduct).delete(controller.deleteProduct);
router.route('/categories').get(controller.categories).post(validateTaxonomy, controller.createCategory);
router.route('/categories/:id').put(validateTaxonomy, controller.updateCategory).delete(controller.deleteCategory);
router.route('/collections').get(controller.collections).post(validateTaxonomy, controller.createCollection);
router.route('/collections/:id').put(validateTaxonomy, controller.updateCollection).delete(controller.deleteCollection);
router.route('/orders').get(controller.orders);
router.get('/orders/:id', controller.order);
router.patch('/orders/:id/status', validateStatus, controller.updateOrderStatus);
router.get('/reviews', controller.reviews);
router.delete('/reviews/:id', controller.deleteReview);
module.exports = router;
